productos = [
    {
        'id': 1,
        'nombre': 'Alimento de gatos Whiskas',
        'detalle': 'comida pa gato',
        'lugar': '$1.000 pesos',
        'hora': 'Disponible',
        'foto': 'https://cdnx.jumpseller.com/la-mascota/image/23058386/Whiskas-Gatito.png?1648570876',
    },
    {
        'id': 2,
        'nombre': 'Recuerdos de Peru',
        'detalle': 'Lindos lugares con pisco chileno',
        'lugar': 'Peru',
        'hora': '11:30 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 3,
        'nombre': 'Recuerdos de CUBA',
        'detalle': 'Sin palabras',
        'lugar': 'Cuba',
        'hora': '19:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 4,
        'nombre': 'Recuerdos de Corea Del Norte',
        'detalle': 'Vi gente sana :) y no pude más...',
        'lugar': 'Corea del Norte',
        'hora': '19:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 5,
        'nombre': 'Recuerdos de Corea Del Sur',
        'detalle': 'No es como aparece en los monitos...',
        'lugar': 'Corea del Sur',
        'hora': '20:20 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 6,
        'nombre': 'Recuerdos de Chile',
        'detalle': 'Un idioma muy especial...',
        'lugar': 'Chile',
        'hora': '15:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
]