productos = [
    {
        'id': 1,
        'nombre': 'Alimento de gatitos Purina CatChow',
        'detalle': 'Comida para gatitos que tengan 2-12 meses de vida, sabor a carnes y leche ',
        'lugar': '$5.000 CLP / x mayor $3.500 CLP',
        'hora': 'Peso: 1kg',
        'foto': 'https://th.bing.com/th/id/OIP.H56QBC0CuMv6PigjesfjTQAAAA?pid=ImgDet&rs=1',
    },
    {
        'id': 2,
        'nombre': 'Alimento de gatos adultos Whiskas',
        'detalle': 'Comida para gatos adultos que tengan +1 año , sabor a pescado ',
        'lugar': '$7.000 CLP / x mayor $4.000 CLP',
        'hora': 'Peso: 8kg',
        'foto': 'https://plazavea.vteximg.com.br/arquivos/ids/228159-450-450/20146570.jpg?v=636995870197130000',
    },
    {
        'id': 3,
        'nombre': 'Recuerdos de CUBA',
        'detalle': 'Sin palabras',
        'lugar': 'Cuba',
        'hora': '19:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 4,
        'nombre': 'Recuerdos de Corea Del Norte',
        'detalle': 'Vi gente sana :) y no pude más...',
        'lugar': 'Corea del Norte',
        'hora': '19:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 5,
        'nombre': 'Recuerdos de Corea Del Sur',
        'detalle': 'No es como aparece en los monitos...',
        'lugar': 'Corea del Sur',
        'hora': '20:20 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 6,
        'nombre': 'Recuerdos de Chile',
        'detalle': 'Un idioma muy especial...',
        'lugar': 'Chile',
        'hora': '15:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 7,
        'nombre': 'Recuerdos de Chile',
        'detalle': 'Un idioma muy especial...',
        'lugar': 'Chile',
        'hora': '15:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 8,
        'nombre': 'Recuerdos de Chile',
        'detalle': 'Un idioma muy especial...',
        'lugar': 'Chile',
        'hora': '15:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 9,
        'nombre': 'Recuerdos de Chile',
        'detalle': 'Un idioma muy especial...',
        'lugar': 'Chile',
        'hora': '15:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 10,
        'nombre': 'Recuerdos de Chile',
        'detalle': 'Un idioma muy especial...',
        'lugar': 'Chile',
        'hora': '15:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 11,
        'nombre': 'Recuerdos de Chile',
        'detalle': 'Un idioma muy especial...',
        'lugar': 'Chile',
        'hora': '15:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
    {
        'id': 12,
        'nombre': 'Recuerdos de Chile',
        'detalle': 'Un idioma muy especial...',
        'lugar': 'Chile',
        'hora': '15:15 AM',
        'foto': 'https://picsum.photos/400/400',
    },
]